 final products = [
  {
    'imagePaths': [
    'assets/images/products/headphones.png',
    'assets/images/products/headphones.png',
    'assets/images/products/headphones.png',
  ],
    'title': 'Беспроводные наушники Baseus Bowie E9',
    'price': '299',
    'oldPrice': '549',
    'badgeText': 'хорошая цена',
    'saleText': '-46%',
    'rating': '4.9',
    'comment': '1320',
  },
  {
    'imagePaths': [
    'assets/images/products/watch.png',
    'assets/images/products/watch.png',
    'assets/images/products/watch.png',
  ],    
  'title': 'Смарт-часы Xiaomi Mi Band 8',
    'price': '349',
    'oldPrice': '549', 
    'badgeText': 'Хит продаж',
    'rating': '4.9',
    'comment': '1320',
  },
  {
    'imagePaths': [
    'assets/images/products/shirt.jpg',
    'assets/images/products/shirt.jpg',
    'assets/images/products/shirt.jpg',
  ],    
    'title': 'Хлопковая футболка Oversize',
    'price': '99',
    'oldPrice': '120',
    'badgeText': 'хорошая цена',
    'saleText': '-21%',
    'rating': '4.8',
    'comment': '812',
  },
  {
    'imagePaths': [
    'assets/images/products/massag.jpg',
    'assets/images/products/massag.jpg',
    'assets/images/products/massag.jpg',
  ],    
    'title': 'Массажный пистолет для тела',
    'price': '449',
    'oldPrice': '549',
    'badgeText': 'хорошая цена',
    'saleText': '-18%',
    'rating': '4.8',
    'comment': '1100+',
  },
  {
    'imagePaths': [
    'assets/images/products/kross.jpg',
    'assets/images/products/kross.jpg',
    'assets/images/products/kross.jpg',
  ],
    'title': 'Кроссовки на толстой подошве',
    'price': '259',
    'oldPrice': '349',
    'badgeText': 'хорошая цена',
    'saleText': '-25%',
    'rating': '4.5',
    'comment': '460',
  },
  {
    'imagePaths': [
    'assets/images/products/window.jpg',
    'assets/images/products/window.jpg',
    'assets/images/products/window.jpg',
  ],    
    'title': 'Зеркало с подсветкой и увеличением',
    'price': '149',
    'oldPrice': '199',
    'badgeText': 'хорошая цена',
    'saleText': '-25%',
    'rating': '4.9',
    'comment': '190',
  },
  {
    'imagePaths': [
    'assets/images/products/box.jpg',
    'assets/images/products/box.jpg',
    'assets/images/products/box.jpg',
  ],    
    'title': 'Органайзер для белья / ящика',
    'price': '69',
    'oldPrice': '99',
    'badgeText': 'хорошая цена',
    'saleText': '-30%',
    'rating': '4.5',
    'comment': '300+',
  },
  {
    'imagePaths': [
    'assets/images/products/lamp.jpg',
    'assets/images/products/lamp.jpg',
    'assets/images/products/lamp.jpg',
  ], 
    'title': 'Мини-проектор для телефона',
    'price': '699',
    'oldPrice': '990',
    'badgeText': 'хорошая цена',
    'saleText': '-30%',
    'rating': '4.8',
    'comment': '1100+',
  },
    {
    'imagePaths': [
    'assets/images/products/led_lamp.jpg',
    'assets/images/products/led_lamp.jpg',
    'assets/images/products/led_lamp.jpg',
  ],    
  'title': 'LED-гирлянда “Звёздное небо”',
    'price': '39',
    'oldPrice': '59',
    'badgeText': 'хорошая цена',
    'saleText': '-33%',
    'rating': '4.7',
    'comment': '780',
  },
    {
    'imagePaths': [
    'assets/images/products/kit_home.jpg',
    'assets/images/products/kit_home.jpg',
    'assets/images/products/kit_home.jpg',
  ],        
  'title': 'Подарочный набор "СПА дома"',
    'price': '199',
    'oldPrice': '239',
    'badgeText': 'хорошая цена',
    'saleText': '-16%',
    'rating': '4.8',
    'comment': '164',
  },

];
